[project]
name = "mail2print"
version = "1.0.0"
description = "Python script to automatically print files sent by an email."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name = "bartekl1"}
]
requires-python = ">=3.11"
dependencies = [
    "imapclient (>=3.1.0,<4.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "pycups (>=2.0.4,<3.0.0)"
]

[project.urls]
homepage = "https://github.com/bartekl1/mail2print"
source = "https://github.com/bartekl1/mail2print"
changelog = "https://github.com/bartekl1/mail2print/releases"
documentation = "https://github.com/bartekl1/mail2print/blob/main/README.md"
issues = "https://github.com/bartekl1/mail2print/issues"

[tool.poetry]
package-mode = false
